In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os
%matplotlib inline

config = tf.ConfigProto(
    gpu_options=tf.GPUOptions(
    allow_growth=True
    ))

In [2]:
# Recovery action の入ったデータ
#'''
r_path = '../data/LOG_G/x1500-y-1100_fix_ball_robot_recovery_action/stable/'
contents = os.listdir(r_path)
data = pd.DataFrame()
num = 0
for c in range(len(contents)):
    print(r_path+contents[c])
    n_data = pd.read_csv(r_path+contents[c],header=None)
    data = pd.concat([data,n_data])
#'''

../data/LOG_G/x1500-y-1100_fix_ball_robot_recovery_action/stable/log201808071317.csv
../data/LOG_G/x1500-y-1100_fix_ball_robot_recovery_action/stable/log201808071320.csv
../data/LOG_G/x1500-y-1100_fix_ball_robot_recovery_action/stable/log201808061458.csv
../data/LOG_G/x1500-y-1100_fix_ball_robot_recovery_action/stable/log201808061526.csv
../data/LOG_G/x1500-y-1100_fix_ball_robot_recovery_action/stable/log201808061727.csv
../data/LOG_G/x1500-y-1100_fix_ball_robot_recovery_action/stable/log201808061453.csv
../data/LOG_G/x1500-y-1100_fix_ball_robot_recovery_action/stable/log201808061510.csv
../data/LOG_G/x1500-y-1100_fix_ball_robot_recovery_action/stable/log201808061520.csv
../data/LOG_G/x1500-y-1100_fix_ball_robot_recovery_action/stable/log201808071200.csv


In [3]:
# ブレることなくボールをゴールに運んだデータ
#'''
target_path = '../data/LOG_G/fix_ball_robot/bk_stable/'
#target_path = '../data/LOG_G/gotya/'
contents = os.listdir(target_path)
num = 0
for c in range(len(contents)):
    print(target_path+contents[c])
    n_data = pd.read_csv(target_path+contents[c],header=None)
    data = pd.concat([data,n_data])

print(len(data))
d = data
#print(ball)
#print(joy)
#'''

../data/LOG_G/fix_ball_robot/bk_stable/log201808031448.csv
../data/LOG_G/fix_ball_robot/bk_stable/log201808031442.csv
../data/LOG_G/fix_ball_robot/bk_stable/log201808031431.csv
../data/LOG_G/fix_ball_robot/bk_stable/log201808031503.csv
../data/LOG_G/fix_ball_robot/bk_stable/log201808031429.csv
../data/LOG_G/fix_ball_robot/bk_stable/log201808031508.csv
../data/LOG_G/fix_ball_robot/bk_stable/log201808031618.csv
59018


In [4]:
d.columns = ['l_bx','l_by','l_pole0x','l_pole0y','l_pole1x','l_pole1y','g_bx','g_by','g_pole0x','g_pole0y','g_pole1x','g_pole1y','g_px','g_py','g_pth','ljx','ljy','rjx','rjy']
#d = d[d.bx!=-1]

In [5]:
'''
from sklearn.cross_validation import train_test_split
t1 = []
t2 = []
def f1(x,y):
    return y * np.sin(x) + np.square(x)
def f2(x,y):
    return x * np.cos(y) + np.square(y)
for a in range(1000):
    r = np.array([np.random.rand(), np.random.rand()])
    t1.append(r)
    t2.append(np.array([ f1(r[0],r[1]),f2(r[0],r[1]) ]))
IN_train, IN_test, TAR_train, TAR_test = train_test_split(t1,t2,test_size=0.2,random_state=0)

IN_train = np.array(IN_train)
IN_test = np.array(IN_test)
TAR_train = np.array(TAR_train)
TAR_test = np.array(TAR_test)
print(IN_train[0])
print(IN_test[0])
print(TAR_train[0])
print(TAR_test[0])
print(f1(1,1))
print(f2(1,1))
'''

'\nfrom sklearn.cross_validation import train_test_split\nt1 = []\nt2 = []\ndef f1(x,y):\n    return y * np.sin(x) + np.square(x)\ndef f2(x,y):\n    return x * np.cos(y) + np.square(y)\nfor a in range(1000):\n    r = np.array([np.random.rand(), np.random.rand()])\n    t1.append(r)\n    t2.append(np.array([ f1(r[0],r[1]),f2(r[0],r[1]) ]))\nIN_train, IN_test, TAR_train, TAR_test = train_test_split(t1,t2,test_size=0.2,random_state=0)\n\nIN_train = np.array(IN_train)\nIN_test = np.array(IN_test)\nTAR_train = np.array(TAR_train)\nTAR_test = np.array(TAR_test)\nprint(IN_train[0])\nprint(IN_test[0])\nprint(TAR_train[0])\nprint(TAR_test[0])\nprint(f1(1,1))\nprint(f2(1,1))\n'

In [6]:
from sklearn.cross_validation import train_test_split

IN_size = 6
TAR_size = 3

l_ball = np.array(d.iloc[:,0:2])   #  0, 1
l_pole0 = np.array(d.iloc[:,2:4])  #  2, 3
l_pole1 = np.array(d.iloc[:,4:6])  #  4, 5
g_ball = np.array(d.iloc[:,6:8])   #  6, 7
g_pole0 = np.array(d.iloc[:,8:10]) #  8, 9
g_pole1 = np.array(d.iloc[:,10:12])# 10,11
g_pos = np.array(d.iloc[:,12:15])  # 12,13,14
ljoy = np.array(d.iloc[:,15:17])   # 15,16
rjoy = np.array(d.iloc[:,17:19])   # 17,18

input_d = np.array(d.iloc[:,0:IN_size])
output_d = np.array(d.iloc[:,15:18])
print(input_d.shape)
print(output_d.shape)



IN_train, IN_test, TAR_train, TAR_test = train_test_split(input_d,output_d,test_size=0.1,random_state=0)
#X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=0)
#IN_train = IN_train/100.0
#IN_test = IN_test/100.0
for t in range(10):
    print(IN_train[t])
'''
print(IN_train[0])
print(IN_test[0])
print(TAR_train[0])
print(TAR_test[0])
'''

(59018, 6)
(59018, 3)
[0.84014753 0.17468594 1.21769852 3.32771447 2.34439603 0.98452162]
[ 0.34259257  0.02941903  1.57175908  1.09243741  0.97990596 -1.43930307]
[ 0.33117676 -0.33743405  3.71230546 -0.94451631  1.69370065 -2.58318487]
[ 0.61591974 -0.1398737   3.56503143  1.27061488  2.74361606 -1.1962205 ]
[ 0.19923238  0.0218821   4.1296325  -0.11664437  2.53298864 -2.16865031]
[1.27779411 0.60440076 0.93755894 4.43087343 3.10383486 2.99308046]
[0.81185694 0.29834927 0.92277427 3.42753301 2.14874231 1.13471763]
[ 0.30064744 -0.10221874  2.61285478  1.4280237   1.89644115 -1.07132652]
[ 0.40105007 -0.10468939  1.76091635  1.35381258  0.69627757 -1.0182212 ]
[1.53980724 0.12048405 2.49826111 4.08668218 4.18298414 2.10635183]


/usr/local/lib/python3.5/dist-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


'\nprint(IN_train[0])\nprint(IN_test[0])\nprint(TAR_train[0])\nprint(TAR_test[0])\n'

In [7]:
#　初期化
sess = tf.Session(config=config)
test_sess = tf.Session(config=config)

INPUT = tf.placeholder(shape=[None, IN_size], dtype=tf.float32)
TARGET = tf.placeholder(shape=[None, TAR_size], dtype=tf.float32)

In [8]:
#hidden_size = [100]
hidden_size = [10,8,5]
batch_size = 100
iter_size = 300000

#　隠れ層の作成 （last layerに直結）
weights = []
biases = []
layers = []
tmp_size = IN_size
last_layer = INPUT
for hsize in hidden_size:
    weights.append(tf.Variable(tf.random_normal(shape=[tmp_size, hsize] ,seed=0.05)))
    biases.append(tf.Variable(tf.random_normal(shape=[hsize],seed=0.05)))
    layers.append(tf.nn.relu(tf.add(tf.matmul(last_layer, weights[-1]), biases[-1]))) # 活性化関数
    tmp_size = hsize
    last_layer = layers[-1]
    print(layers[-1])
#　出力層
weights.append(tf.Variable(tf.random_normal(shape=[tmp_size, TAR_size],seed=0.05)))
biases.append(tf.Variable(tf.random_normal(shape=[TAR_size],seed=0.05)))
layers.append(tf.add(tf.matmul(last_layer, weights[-1]), biases[-1]))
final_output = layers[-1]
print(final_output)

Tensor("Relu:0", shape=(?, 10), dtype=float32)
Tensor("Relu_1:0", shape=(?, 8), dtype=float32)
Tensor("Relu_2:0", shape=(?, 5), dtype=float32)
Tensor("Add_3:0", shape=(?, 3), dtype=float32)


In [9]:
#　学習
loss = tf.losses.mean_squared_error(TARGET,final_output)
test_loss = tf.losses.mean_squared_error(TARGET,final_output)
opt = tf.train.AdamOptimizer(0.001)
#opt = tf.train.GradientDescentOptimizer(0.01)
train_step = opt.minimize(loss)
init = tf.global_variables_initializer()
sess.run(init)
test_sess.run(init)
loss_vec=[]
test_loss_vec=[]
for i in range(iter_size):
    train_rand_index = np.random.choice(len(IN_train), size=batch_size,replace=False)
    train_rand_in = IN_train[train_rand_index]
    train_rand_tar = TAR_train[train_rand_index]
    sess.run(train_step, feed_dict={INPUT:train_rand_in, TARGET: train_rand_tar})
    loss_vec.append(sess.run(loss, feed_dict={INPUT:train_rand_in, TARGET: train_rand_tar}))
    
    test_rand_index = np.random.choice(len(IN_test), size=batch_size,replace=False)
    test_rand_in = IN_test[test_rand_index]
    test_rand_tar = TAR_test[test_rand_index]
    test_sess.run(train_step, feed_dict={INPUT:test_rand_in, TARGET: test_rand_tar})
    test_loss_vec.append(test_sess.run(test_loss, feed_dict={INPUT:test_rand_in, TARGET: test_rand_tar}))
    
    if (i+1)%25==0:
#        print(sess.run(INPUT, feed_dict={INPUT:rand_in, TARGET: rand_tar}))
        print('Generation:'+str(i+1)+', Loss = '+str(loss_vec[-1]))

Generation:25, Loss = 7.4570785
Generation:50, Loss = 3.130268
Generation:75, Loss = 2.3773928
Generation:100, Loss = 1.9959588
Generation:125, Loss = 1.9760025
Generation:150, Loss = 1.7484655
Generation:175, Loss = 1.7054181
Generation:200, Loss = 1.695094
Generation:225, Loss = 1.5322179
Generation:250, Loss = 1.7139579
Generation:275, Loss = 1.5253013
Generation:300, Loss = 1.5498767
Generation:325, Loss = 1.434422
Generation:350, Loss = 1.3138745
Generation:375, Loss = 1.2723198
Generation:400, Loss = 1.1039225
Generation:425, Loss = 1.0247449
Generation:450, Loss = 1.3426967
Generation:475, Loss = 0.8091474
Generation:500, Loss = 0.54810673
Generation:525, Loss = 0.42997208
Generation:550, Loss = 0.36755523
Generation:575, Loss = 0.40719873
Generation:600, Loss = 0.3603264
Generation:625, Loss = 0.35851935
Generation:650, Loss = 0.32256055
Generation:675, Loss = 0.30410206
Generation:700, Loss = 0.28969616
Generation:725, Loss = 0.28804654
Generation:750, Loss = 0.2687922
Generat

Generation:5925, Loss = 0.08699527
Generation:5950, Loss = 0.06532486
Generation:5975, Loss = 0.081323355
Generation:6000, Loss = 0.07778909
Generation:6025, Loss = 0.090714455
Generation:6050, Loss = 0.08168479
Generation:6075, Loss = 0.08400788
Generation:6100, Loss = 0.08436344
Generation:6125, Loss = 0.079197384
Generation:6150, Loss = 0.09025486
Generation:6175, Loss = 0.06885262
Generation:6200, Loss = 0.07585103
Generation:6225, Loss = 0.10124251
Generation:6250, Loss = 0.087207064
Generation:6275, Loss = 0.082026444
Generation:6300, Loss = 0.07968656
Generation:6325, Loss = 0.08261475
Generation:6350, Loss = 0.10206573
Generation:6375, Loss = 0.09200955
Generation:6400, Loss = 0.08981006
Generation:6425, Loss = 0.06966607
Generation:6450, Loss = 0.0826787
Generation:6475, Loss = 0.0800234
Generation:6500, Loss = 0.09076954
Generation:6525, Loss = 0.08648077
Generation:6550, Loss = 0.075901546
Generation:6575, Loss = 0.08275618
Generation:6600, Loss = 0.0830843
Generation:6625, 

Generation:11725, Loss = 0.073421374
Generation:11750, Loss = 0.06421025
Generation:11775, Loss = 0.057760652
Generation:11800, Loss = 0.074388444
Generation:11825, Loss = 0.070428774
Generation:11850, Loss = 0.073072165
Generation:11875, Loss = 0.079537734
Generation:11900, Loss = 0.06965375
Generation:11925, Loss = 0.078184195
Generation:11950, Loss = 0.06996333
Generation:11975, Loss = 0.0672838
Generation:12000, Loss = 0.058398858
Generation:12025, Loss = 0.06999617
Generation:12050, Loss = 0.055673346
Generation:12075, Loss = 0.08705205
Generation:12100, Loss = 0.06141406
Generation:12125, Loss = 0.06691497
Generation:12150, Loss = 0.07619909
Generation:12175, Loss = 0.07237147
Generation:12200, Loss = 0.052868977
Generation:12225, Loss = 0.08244948
Generation:12250, Loss = 0.073088534
Generation:12275, Loss = 0.07283406
Generation:12300, Loss = 0.06682578
Generation:12325, Loss = 0.072658665
Generation:12350, Loss = 0.057585806
Generation:12375, Loss = 0.06705461
Generation:12400

Generation:17425, Loss = 0.071442455
Generation:17450, Loss = 0.07129505
Generation:17475, Loss = 0.074097484
Generation:17500, Loss = 0.05900152
Generation:17525, Loss = 0.07485786
Generation:17550, Loss = 0.058772177
Generation:17575, Loss = 0.06717815
Generation:17600, Loss = 0.08413827
Generation:17625, Loss = 0.06762536
Generation:17650, Loss = 0.068406545
Generation:17675, Loss = 0.06781721
Generation:17700, Loss = 0.06508856
Generation:17725, Loss = 0.064896256
Generation:17750, Loss = 0.06030581
Generation:17775, Loss = 0.068119474
Generation:17800, Loss = 0.06827661
Generation:17825, Loss = 0.07265881
Generation:17850, Loss = 0.05429479
Generation:17875, Loss = 0.06749929
Generation:17900, Loss = 0.061052833
Generation:17925, Loss = 0.074111044
Generation:17950, Loss = 0.05138472
Generation:17975, Loss = 0.07746403
Generation:18000, Loss = 0.06736215
Generation:18025, Loss = 0.05162489
Generation:18050, Loss = 0.057040114
Generation:18075, Loss = 0.08084348
Generation:18100, L

Generation:23075, Loss = 0.059565213
Generation:23100, Loss = 0.05160161
Generation:23125, Loss = 0.060051244
Generation:23150, Loss = 0.06754331
Generation:23175, Loss = 0.0680213
Generation:23200, Loss = 0.07221719
Generation:23225, Loss = 0.065180674
Generation:23250, Loss = 0.06640776
Generation:23275, Loss = 0.06378277
Generation:23300, Loss = 0.07264319
Generation:23325, Loss = 0.06841923
Generation:23350, Loss = 0.062640324
Generation:23375, Loss = 0.07297687
Generation:23400, Loss = 0.059597913
Generation:23425, Loss = 0.05965912
Generation:23450, Loss = 0.06477066
Generation:23475, Loss = 0.058044575
Generation:23500, Loss = 0.065375306
Generation:23525, Loss = 0.07265186
Generation:23550, Loss = 0.050740145
Generation:23575, Loss = 0.07825849
Generation:23600, Loss = 0.06680716
Generation:23625, Loss = 0.066730045
Generation:23650, Loss = 0.0524977
Generation:23675, Loss = 0.07863459
Generation:23700, Loss = 0.07213215
Generation:23725, Loss = 0.070344865
Generation:23750, Lo

Generation:28725, Loss = 0.062891625
Generation:28750, Loss = 0.059387233
Generation:28775, Loss = 0.07010787
Generation:28800, Loss = 0.0543518
Generation:28825, Loss = 0.05531875
Generation:28850, Loss = 0.06399122
Generation:28875, Loss = 0.05554252
Generation:28900, Loss = 0.06896624
Generation:28925, Loss = 0.062651865
Generation:28950, Loss = 0.057016507
Generation:28975, Loss = 0.07636314
Generation:29000, Loss = 0.057983994
Generation:29025, Loss = 0.065271854
Generation:29050, Loss = 0.05674211
Generation:29075, Loss = 0.06096381
Generation:29100, Loss = 0.05206161
Generation:29125, Loss = 0.07762343
Generation:29150, Loss = 0.060547728
Generation:29175, Loss = 0.06753055
Generation:29200, Loss = 0.047714606
Generation:29225, Loss = 0.051442936
Generation:29250, Loss = 0.07090664
Generation:29275, Loss = 0.07214241
Generation:29300, Loss = 0.057282716
Generation:29325, Loss = 0.056293406
Generation:29350, Loss = 0.0731879
Generation:29375, Loss = 0.06450562
Generation:29400, L

Generation:34375, Loss = 0.061205566
Generation:34400, Loss = 0.07445472
Generation:34425, Loss = 0.072380416
Generation:34450, Loss = 0.057181116
Generation:34475, Loss = 0.05405301
Generation:34500, Loss = 0.07315127
Generation:34525, Loss = 0.05932497
Generation:34550, Loss = 0.068540595
Generation:34575, Loss = 0.05560009
Generation:34600, Loss = 0.056599516
Generation:34625, Loss = 0.06459974
Generation:34650, Loss = 0.057841886
Generation:34675, Loss = 0.058219675
Generation:34700, Loss = 0.07308899
Generation:34725, Loss = 0.06407625
Generation:34750, Loss = 0.06539793
Generation:34775, Loss = 0.048852816
Generation:34800, Loss = 0.062254116
Generation:34825, Loss = 0.06707359
Generation:34850, Loss = 0.0584748
Generation:34875, Loss = 0.06358855
Generation:34900, Loss = 0.06267184
Generation:34925, Loss = 0.0519801
Generation:34950, Loss = 0.0653776
Generation:34975, Loss = 0.060865592
Generation:35000, Loss = 0.05366578
Generation:35025, Loss = 0.053113718
Generation:35050, Lo

Generation:40000, Loss = 0.06111566
Generation:40025, Loss = 0.06230215
Generation:40050, Loss = 0.067662
Generation:40075, Loss = 0.05601406
Generation:40100, Loss = 0.055054914
Generation:40125, Loss = 0.063043356
Generation:40150, Loss = 0.05105427
Generation:40175, Loss = 0.072126806
Generation:40200, Loss = 0.07788115
Generation:40225, Loss = 0.07146044
Generation:40250, Loss = 0.05043481
Generation:40275, Loss = 0.059229787
Generation:40300, Loss = 0.06459456
Generation:40325, Loss = 0.057235807
Generation:40350, Loss = 0.061697412
Generation:40375, Loss = 0.060444526
Generation:40400, Loss = 0.0591845
Generation:40425, Loss = 0.07418701
Generation:40450, Loss = 0.061745726
Generation:40475, Loss = 0.056130525
Generation:40500, Loss = 0.06304813
Generation:40525, Loss = 0.06585279
Generation:40550, Loss = 0.07536686
Generation:40575, Loss = 0.056311328
Generation:40600, Loss = 0.07131398
Generation:40625, Loss = 0.054810777
Generation:40650, Loss = 0.064691834
Generation:40675, L

Generation:45650, Loss = 0.05492794
Generation:45675, Loss = 0.051804416
Generation:45700, Loss = 0.058931604
Generation:45725, Loss = 0.067901105
Generation:45750, Loss = 0.060892727
Generation:45775, Loss = 0.061979305
Generation:45800, Loss = 0.062838525
Generation:45825, Loss = 0.056985855
Generation:45850, Loss = 0.05883007
Generation:45875, Loss = 0.059048068
Generation:45900, Loss = 0.06180135
Generation:45925, Loss = 0.07067883
Generation:45950, Loss = 0.067425996
Generation:45975, Loss = 0.0624284
Generation:46000, Loss = 0.059202507
Generation:46025, Loss = 0.050296452
Generation:46050, Loss = 0.05446048
Generation:46075, Loss = 0.055116832
Generation:46100, Loss = 0.06310095
Generation:46125, Loss = 0.058729272
Generation:46150, Loss = 0.060651008
Generation:46175, Loss = 0.062686704
Generation:46200, Loss = 0.063164644
Generation:46225, Loss = 0.06256632
Generation:46250, Loss = 0.049761254
Generation:46275, Loss = 0.068099685
Generation:46300, Loss = 0.056882802
Generation

KeyboardInterrupt: 

In [ ]:
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
plt.grid()
plt.plot(loss_vec,c='b',linestyle='solid',label='train loss')
plt.plot(test_loss_vec,c='r',label='test loss')

#plt.xlim(60000,60100)
plt.ylim(0,0.5)
ax.set_xlabel('iteration')
ax.set_ylabel('loss')
plt.savefig(str(hidden_size)+'.png')
plt.legend()


#print(test_loss_vec[99999])
#print(test_loss_vec[99999])

In [ ]:
# 重みの保存
saver = tf.train.Saver()
saver.save(sess, './model.ckpt')


In [ ]:
'''
# ボール座標とスティックの傾きプロット
by_max=IN_train.max(axis=0)[1]
by_min=IN_train.min(axis=0)[1]

ball_y = np.array(range(int(by_min)-3,int(by_max)+3))
for i in range(len(ball_y)):
    
    ball = np.array([[6.0, ball_y[i]/10.0]])
    
    print(ball)
    joy = sess.run(final_output, feed_dict={INPUT: ball})
    plt.scatter(ball[0][1],ball[0][0], s=200, c='orange')
    
    plt.quiver(0,0,-joy[0][0],-joy[0][1],angles="xy",scale_units="xy",scale=1)
    #plt.quiver(0,0,-0.6,5,angles="xy",scale_units="xy",scale=1)
    print(joy)
    plt.savefig(str(hidden_size)+'_img'+'.png')
    '''

In [ ]:
# 重みのrestore
predicts_sess = tf.Session(config=config)
ckpt = tf.train.get_checkpoint_state('./')
if ckpt == None:
    print('!!!!!!!WEIGHTS NOT FOUND!!!!!!')

saver.restore(predicts_sess, './model.ckpt')