In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
%matplotlib inline

ratio = 150
r_field_w = 9000
r_field_h = 6000
r_center_circle_pos=[int(r_field_w/2),int(r_field_h/2)]
r_center_circle_radius = 1500
r_goal_line_left_upper = [0, (r_field_h-5000)/2]
r_goal_line_right_lower = [1000, (r_field_h-1000)/2 + 5000]
field_w = int(r_field_w/ratio)
field_h = int(r_field_h/ratio)
center_circle_pos = [int(field_w/2), int(field_h/2)]
center_circle_radius = int(r_center_circle_radius/ratio)
goal_line_left_upper = [int(r_goal_line_left_upper[0]/ratio), int(r_goal_line_left_upper[1]/ratio)]
goal_line_right_lower = [int(r_goal_line_right_lower[0]/ratio), goal_line_left_upper[1]+int(5000/ratio)]
print(goal_line_left_upper)
print(goal_line_right_lower)
mergin = 10
img=np.zeros((field_h + mergin, field_w + mergin, 3), np.uint8)
img[:,:,1]=255  
cv2.imwrite('gereen.png',img)
print(img.shape)
print(center_circle_pos[0])

[0, 3]
[6, 36]
(50, 70, 3)
30


# 外枠

In [2]:
print(field_w+int(mergin/2),field_h+int(mergin/2))
cv2.rectangle(img, (int(mergin/2), int(mergin/2)), (field_w+int(mergin/2), field_h+int(mergin/2)), (255, 0, 0))

65 45


array([[[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       ...,

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]]

# センターサークル

In [3]:
print(center_circle_radius)
cv2.ellipse(img, ((center_circle_pos[0]+int(mergin/2),center_circle_pos[1]+int(mergin/2)), (center_circle_radius,center_circle_radius), 0),(255, 0, 0))

10


array([[[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       ...,

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]]

# センターライン

In [4]:
print(int(mergin/2)+int(field_w/2), int(mergin/2))
print((int(mergin/2)+int(field_w/2), int(mergin/2)+int(field_h)))
cv2.line(img, (int(mergin/2)+int(field_w/2), int(mergin/2)), (int(mergin/2)+int(field_w/2), int(mergin/2)+int(field_h)), (255, 0, 0))

35 5
(35, 45)


array([[[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       ...,

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]]

# ゴールライン1 

In [5]:
print((int(mergin/2)+goal_line_left_upper[0], int(mergin/2)+goal_line_left_upper[1]))
print((goal_line_right_lower[0]+int(mergin/2), goal_line_right_lower[1]+int(mergin/2)))
cv2.rectangle(img, (int(mergin/2)+goal_line_left_upper[0], int(mergin/2)+goal_line_left_upper[1]), (goal_line_right_lower[0]+int(mergin/2), goal_line_right_lower[1]+int(mergin/2)), (255, 0, 0))
#print(field_w+int(mergin/2)-int(mergin/2)+goal_line_left_upper[0],int(mergin/2)+goal_line_left_upper[1])
#print((goal_line_right_lower[0]+int(mergin/2), goal_line_right_lower[1]+int(mergin/2)))
#cv2.rectangle(img, (field_w+int(mergin/2)-int(mergin/2)+goal_line_left_upper[0],int(mergin/2)+goal_line_left_upper[1]), (goal_line_right_lower[0]+int(mergin/2), goal_line_right_lower[1]+int(mergin/2)), (255, 0, 0))

(5, 8)
(11, 41)


array([[[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       ...,

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]]

# ゴールライン2

In [6]:
print(field_w -goal_line_right_lower[0],  int(mergin/2)+goal_line_left_upper[1])
print((field_w+int(mergin/2)-(int(mergin/2)), goal_line_right_lower[1]+int(mergin/2)))
cv2.rectangle(img, (field_w -goal_line_right_lower[0]+int(mergin/2),  int(mergin/2)+goal_line_left_upper[1]), (field_w+int(mergin/2), goal_line_right_lower[1]+int(mergin/2)), (255, 0, 0))

54 8
(60, 41)


array([[[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       ...,

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]]

In [7]:
cv2.imwrite('gereen.png',img)

True

In [8]:
t = [0,0,0]